export const QUERY_KEY = {
  todoList: 'todoList',
  favorite: 'favorite',
  recommend: 'recommend',
  recommendLimit: 'recommendLimit',
  recommendAll: 'recommendAll',
  routeTodoList: 'routeTodoList',
  searchAddress: 'searchAddress',
  searchRoutes: 'searchRoutes',
  todayAchievement: 'todayAchievement',
  planInfo: 'planInfo',
  memberAddress: 'memberAddress',
  detailTodo: 'detailTodo',
  nearbyUsers: 'nearbyUsers',
  memberStatus: 'memberStatus',
  memberInfo: 'memberInfo',
} as const;
