server:
  port: 8080
  servlet:
    contextPath: /api/v1

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 10
      password: ""

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

oauth2:
  client:
    registration:
      kakao:
        client_id: ${KAKAO_CLIENT_ID} # REST API
        redirect_uri: ${KAKAO_REDIRECT_URI}
        client_secret: ${KAKAO_CLIENT_SECRET} # Client Secret
        scope: account_email
    provider:
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time-in-hours: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-expire-time-in-hours: ${JWT_REFRESH_TOKEN_TIME}

naver:
  client:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

odsay:
  client:
    api-key: ${ODSAY_CLIENT_API_KEY}

logging:
  level:
    root: info
    com.p6spy: debug